import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Script from "next/script";
import "./globals.css";

import NextTopLoader from "nextjs-toploader";
import ReduxProvider from "@/providers/ReduxProvider";
import { Toaster } from "@/components/ui/sonner";
import BasicLayout from "@/layout/BasicLaypout";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Quartus Global Services",
  description: "Generated by create next app",
  icons: {
    icon: "/Fevicon.svg",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/Fevicon.svg" type="image/svg+xml" />
      </head>

      <body className={`${poppins.variable} antialiased overflow-x-hidden`}>
        <ReduxProvider>
          <BasicLayout>{children}</BasicLayout>
          <Toaster />
        </ReduxProvider>

        <NextTopLoader />

        {/* ✅ Tawk.to Script (HTML equivalent) */}
        <Script
          id="tawk-script"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              var Tawk_API = Tawk_API || {}, Tawk_LoadStart = new Date();
              (function() {
                var s1 = document.createElement("script"),
                    s0 = document.getElementsByTagName("script")[0];
                s1.async = true;
                s1.src = "https://embed.tawk.to/69407e4e18f23b1985edab5d/1jchuqp3b";
                s1.charset = "UTF-8";
                s1.setAttribute("crossorigin", "*");
                s0.parentNode.insertBefore(s1, s0);
              })();
            `,
          }}
        />
      </body>
    </html>
  );
}
