// utils/countryMap.ts
export const countrySlugToCode: Record<string, string> = {
  // Core
  india: "IN",
  "united-states": "US",
  "united-kingdom": "GB",

  // Destinations
  brazil: "BR",
  kenya: "KE",
  tanzania: "TZ",
  turkey: "TR",
  vietnam: "VN",

  // eVisa Countries
  australia: "AU",
  azerbaijan: "AZ",
  bahrain: "BH",
  benin: "BJ",
  cambodia: "KH",
  "cote-divoire": "CI",
  egypt: "EG",
  ethiopia: "ET",
  iraq: "IQ",
  japan: "JP",
  jordan: "JO",
  kuwait: "KW",
  kyrgyzstan: "KG",
  laos: "LA",
  morocco: "MA",
  mozambique: "MZ",
  myanmar: "MM",
  namibia: "NA",
  "new-zealand": "NZ",
  nigeria: "NG",
  oman: "OM",
  pakistan: "PK",
  rwanda: "RW",
  "saudi-arabia": "SA",
  "south-korea": "KR",
  "sri-lanka": "LK",
  tajikistan: "TJ",
  thailand: "TH",
  uganda: "UG",
  "united-arab-emirates": "AE",
  uzbekistan: "UZ",
  zambia: "ZM",
};
